{
    "model_class": "Job",
    "id": "0f5a61fdcbb69dc5",
    "history_id": "c8116a80fa28fd2f",
    "tool_id": "toolshed.g2.bx.psu.edu/repos/bgruening/flye/flye/2.9.4+galaxy0",
    "state": "error",
    "exit_code": null,
    "create_time": "2024-10-11T06:53:15.825885",
    "update_time": "2024-10-11T06:53:36.396769",
    "galaxy_version": "24.1",
    "external_id": "gxy-6lnpd",
    "handler": null,
    "job_runner_name": null,
    "command_line": "ln -sf '/galaxy/server/database/objects/8/b/8/dataset_8b81d640-2924-4b86-925a-ff426420a302.dat' ./input_0.fastq.gz && ln -sf '/galaxy/server/database/objects/b/b/5/dataset_bb52ea9a-63c7-4a29-9084-e5d1491c2e9d.dat' ./input_1.fastq.gz && ln -sf '/galaxy/server/database/objects/a/1/1/dataset_a119405e-5b2c-4527-806a-8cb6a6019664.dat' ./input_2.fastq.gz && ln -sf '/galaxy/server/database/objects/0/3/0/dataset_030db9e8-32b0-47f7-94cb-7b6f4698eecd.dat' ./input_3.fastq.gz && ln -sf '/galaxy/server/database/objects/3/3/6/dataset_336a5131-ab12-446d-a680-1246c4bf8af3.dat' ./input_4.fastq.gz && ln -sf '/galaxy/server/database/objects/d/d/8/dataset_dd896844-592a-4e42-8ea9-d4c871718e5a.dat' ./input_5.fastq.gz && ln -sf '/galaxy/server/database/objects/5/d/8/dataset_5d8022f5-1415-4cdc-a55d-2a41ed27b975.dat' ./input_6.fastq.gz && ln -sf '/galaxy/server/database/objects/d/8/9/dataset_d89e8383-70a0-42ca-88a5-8132cd898855.dat' ./input_7.fastq.gz && ln -sf '/galaxy/server/database/objects/9/1/6/dataset_916f42b8-a898-44e5-bd8c-ab90a3909dec.dat' ./input_8.fastq.gz && flye --pacbio-hifi ./input_0.fastq.gz ./input_1.fastq.gz ./input_2.fastq.gz ./input_3.fastq.gz ./input_4.fastq.gz ./input_5.fastq.gz ./input_6.fastq.gz ./input_7.fastq.gz ./input_8.fastq.gz -o out_dir -t ${GALAXY_SLOTS:-4} -i 1 --hifi-error 0.21 -m 1000",
    "user_email": "tests@fake.org",
    "command_version": null,
    "params": {
        "__input_ext": "\"input\"",
        "dbkey": "\"?\"",
        "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",
        "generate_log": "false",
        "no_alt_contigs": "false",
        "asm": "{\"__current_case__\": 1, \"asm_select\": \"false\"}",
        "meta": "false",
        "scaffold": "false",
        "keep_haplotypes": "false",
        "min_overlap": "\"1000\"",
        "iterations": "\"1\"",
        "mode_conditional": "{\"__current_case__\": 5, \"hifi_error\": \"0.21\", \"mode\": \"--pacbio-hifi\"}"
    },
    "inputs": {
        "inputs9": {
            "id": "c4d0bf222cd6d45e",
            "src": "hda",
            "uuid": "916f42b8-a898-44e5-bd8c-ab90a3909dec"
        },
        "inputs8": {
            "id": "59d6bbb66371c76b",
            "src": "hda",
            "uuid": "d89e8383-70a0-42ca-88a5-8132cd898855"
        },
        "inputs7": {
            "id": "041c8898c1996c28",
            "src": "hda",
            "uuid": "5d8022f5-1415-4cdc-a55d-2a41ed27b975"
        },
        "inputs6": {
            "id": "98e0d43c8e2a4bfb",
            "src": "hda",
            "uuid": "dd896844-592a-4e42-8ea9-d4c871718e5a"
        },
        "inputs5": {
            "id": "d4c98b8d9d04546a",
            "src": "hda",
            "uuid": "336a5131-ab12-446d-a680-1246c4bf8af3"
        },
        "inputs4": {
            "id": "c6a29d0b63f50682",
            "src": "hda",
            "uuid": "030db9e8-32b0-47f7-94cb-7b6f4698eecd"
        },
        "inputs3": {
            "id": "f371aa0d4553a071",
            "src": "hda",
            "uuid": "a119405e-5b2c-4527-806a-8cb6a6019664"
        },
        "inputs2": {
            "id": "f23dd03a8fa3cd00",
            "src": "hda",
            "uuid": "bb52ea9a-63c7-4a29-9084-e5d1491c2e9d"
        },
        "inputs1": {
            "id": "99ab31fca09fbe83",
            "src": "hda",
            "uuid": "8b81d640-2924-4b86-925a-ff426420a302"
        },
        "inputs": {
            "id": "99ab31fca09fbe83",
            "src": "hda",
            "uuid": "8b81d640-2924-4b86-925a-ff426420a302"
        }
    },
    "outputs": {
        "assembly_info": {
            "id": "98371092c40996bf",
            "src": "hda",
            "uuid": "49c376c0-12b5-4393-b203-757af4db77db"
        },
        "assembly_gfa": {
            "id": "1127b7e8a2983d37",
            "src": "hda",
            "uuid": "fbbe7264-6b59-4fe3-bcb5-370a5a7c01f7"
        },
        "assembly_graph": {
            "id": "4811362edf58f833",
            "src": "hda",
            "uuid": "59ba19ee-27c3-40ef-b5e0-c7d5163561f1"
        },
        "consensus": {
            "id": "cbbe2b2e7c8e0665",
            "src": "hda",
            "uuid": "008f7066-699f-4881-bcfd-a5148afcbff1"
        }
    },
    "copied_from_job_id": null,
    "output_collections": {},
    "tool_stdout": "",
    "tool_stderr": "[2024-10-11 06:53:18] INFO: Starting Flye 2.9.4-b1799\n[2024-10-11 06:53:18] INFO: >>>STAGE: configure\n[2024-10-11 06:53:18] INFO: Configuring run\n[2024-10-11 06:53:18] INFO: Total read length: 6522170\n[2024-10-11 06:53:18] INFO: Reads N50/N90: 2706 / 1386\n[2024-10-11 06:53:18] INFO: Selected minimum overlap: 1000\n[2024-10-11 06:53:18] INFO: >>>STAGE: assembly\n[2024-10-11 06:53:18] INFO: Assembling disjointigs\n[2024-10-11 06:53:18] INFO: Reading sequences\n[2024-10-11 06:53:18] INFO: Building minimizer index\n[2024-10-11 06:53:18] INFO: Pre-calculating index storage\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:53:18] INFO: Filling index\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:53:19] INFO: Extending reads\n[2024-10-11 06:53:21] INFO: Overlap-based coverage: 12\n[2024-10-11 06:53:21] INFO: Median overlap divergence: 0.0135674\n0% 20% 30% 40% 60% 80% 90% 100% \n[2024-10-11 06:53:21] INFO: Assembled 12 disjointigs\n[2024-10-11 06:53:21] INFO: Generating sequence\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:53:21] INFO: Filtering contained disjointigs\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:53:22] INFO: Contained seqs: 0\n[2024-10-11 06:53:22] INFO: >>>STAGE: consensus\n[2024-10-11 06:53:22] INFO: Running Minimap2\n[2024-10-11 06:53:22] INFO: Computing consensus\n[2024-10-11 06:53:23] INFO: Alignment error rate: 0.018187\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000f6037a000000ac'\n[2024-10-11 06:53:23] INFO: >>>STAGE: repeat\n[2024-10-11 06:53:23] INFO: Building and resolving repeat graph\n[2024-10-11 06:53:23] INFO: Parsing disjointigs\n[2024-10-11 06:53:23] INFO: Building repeat graph\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:53:23] INFO: Median overlap divergence: 0.00160013\n[2024-10-11 06:53:23] INFO: Parsing reads\n[2024-10-11 06:53:24] INFO: Aligning reads to the graph\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:53:24] INFO: Aligned read sequence: 6400859 / 6522170 (0.9814)\n[2024-10-11 06:53:24] INFO: Median overlap divergence: 0.00693005\n[2024-10-11 06:53:24] INFO: Mean edge coverage: 14\n[2024-10-11 06:53:24] INFO: Simplifying the graph\n[2024-10-11 06:53:24] INFO: >>>STAGE: contigger\n[2024-10-11 06:53:24] INFO: Generating contigs\n[2024-10-11 06:53:24] INFO: Reading sequences\n[2024-10-11 06:53:24] INFO: Generated 5 contigs\n[2024-10-11 06:53:24] INFO: Added 0 scaffold connections\n[2024-10-11 06:53:24] INFO: >>>STAGE: polishing\n[2024-10-11 06:53:24] INFO: Polishing genome (1/1)\n[2024-10-11 06:53:24] INFO: Running minimap2\n[2024-10-11 06:53:25] INFO: Separating alignment into bubbles\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000f6038f000000ad'\n[2024-10-11 06:53:26] INFO: Alignment error rate: 0.010368\n[2024-10-11 06:53:26] INFO: Correcting bubbles\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000f6039d000000ae'\n[2024-10-11 06:53:33] INFO: >>>STAGE: finalize\n[2024-10-11 06:53:33] INFO: Assembly statistics:\n\n\tTotal length:\t418245\n\tFragments:\t5\n\tFragments N50:\t90298\n\tLargest frg:\t147965\n\tScaffolds:\t0\n\tMean coverage:\t16\n\n[2024-10-11 06:53:33] INFO: Final assembly: /galaxy/server/database/jobs_directory/000/120/working/out_dir/assembly.fasta\n",
    "job_stdout": null,
    "job_stderr": null,
    "stdout": "",
    "stderr": "[2024-10-11 06:53:18] INFO: Starting Flye 2.9.4-b1799\n[2024-10-11 06:53:18] INFO: >>>STAGE: configure\n[2024-10-11 06:53:18] INFO: Configuring run\n[2024-10-11 06:53:18] INFO: Total read length: 6522170\n[2024-10-11 06:53:18] INFO: Reads N50/N90: 2706 / 1386\n[2024-10-11 06:53:18] INFO: Selected minimum overlap: 1000\n[2024-10-11 06:53:18] INFO: >>>STAGE: assembly\n[2024-10-11 06:53:18] INFO: Assembling disjointigs\n[2024-10-11 06:53:18] INFO: Reading sequences\n[2024-10-11 06:53:18] INFO: Building minimizer index\n[2024-10-11 06:53:18] INFO: Pre-calculating index storage\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:53:18] INFO: Filling index\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:53:19] INFO: Extending reads\n[2024-10-11 06:53:21] INFO: Overlap-based coverage: 12\n[2024-10-11 06:53:21] INFO: Median overlap divergence: 0.0135674\n0% 20% 30% 40% 60% 80% 90% 100% \n[2024-10-11 06:53:21] INFO: Assembled 12 disjointigs\n[2024-10-11 06:53:21] INFO: Generating sequence\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:53:21] INFO: Filtering contained disjointigs\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:53:22] INFO: Contained seqs: 0\n[2024-10-11 06:53:22] INFO: >>>STAGE: consensus\n[2024-10-11 06:53:22] INFO: Running Minimap2\n[2024-10-11 06:53:22] INFO: Computing consensus\n[2024-10-11 06:53:23] INFO: Alignment error rate: 0.018187\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000f6037a000000ac'\n[2024-10-11 06:53:23] INFO: >>>STAGE: repeat\n[2024-10-11 06:53:23] INFO: Building and resolving repeat graph\n[2024-10-11 06:53:23] INFO: Parsing disjointigs\n[2024-10-11 06:53:23] INFO: Building repeat graph\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:53:23] INFO: Median overlap divergence: 0.00160013\n[2024-10-11 06:53:23] INFO: Parsing reads\n[2024-10-11 06:53:24] INFO: Aligning reads to the graph\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \n[2024-10-11 06:53:24] INFO: Aligned read sequence: 6400859 / 6522170 (0.9814)\n[2024-10-11 06:53:24] INFO: Median overlap divergence: 0.00693005\n[2024-10-11 06:53:24] INFO: Mean edge coverage: 14\n[2024-10-11 06:53:24] INFO: Simplifying the graph\n[2024-10-11 06:53:24] INFO: >>>STAGE: contigger\n[2024-10-11 06:53:24] INFO: Generating contigs\n[2024-10-11 06:53:24] INFO: Reading sequences\n[2024-10-11 06:53:24] INFO: Generated 5 contigs\n[2024-10-11 06:53:24] INFO: Added 0 scaffold connections\n[2024-10-11 06:53:24] INFO: >>>STAGE: polishing\n[2024-10-11 06:53:24] INFO: Polishing genome (1/1)\n[2024-10-11 06:53:24] INFO: Running minimap2\n[2024-10-11 06:53:25] INFO: Separating alignment into bubbles\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000f6038f000000ad'\n[2024-10-11 06:53:26] INFO: Alignment error rate: 0.010368\n[2024-10-11 06:53:26] INFO: Correcting bubbles\n0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% \nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 600, in _run_server\n    server.serve_forever()\n  File \"/usr/local/lib/python3.11/multiprocessing/managers.py\", line 184, in serve_forever\n    sys.exit(0)\nSystemExit: 0\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 303, in _run_finalizers\n    finalizer()\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 227, in __call__\n    res = self._callback(*self._args, **self._kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/multiprocessing/util.py\", line 136, in _remove_temp_dir\n    rmtree(tempdir, onerror=onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 752, in rmtree\n    _rmtree_safe_fd(fd, path, onerror)\n  File \"/usr/local/lib/python3.11/shutil.py\", line 703, in _rmtree_safe_fd\n    onerror(os.unlink, fullname, sys.exc_info())\n  File \"/usr/local/lib/python3.11/shutil.py\", line 701, in _rmtree_safe_fd\n    os.unlink(entry.name, dir_fd=topfd)\nOSError: [Errno 16] Device or resource busy: '.nfs0000000000f6039d000000ae'\n[2024-10-11 06:53:33] INFO: >>>STAGE: finalize\n[2024-10-11 06:53:33] INFO: Assembly statistics:\n\n\tTotal length:\t418245\n\tFragments:\t5\n\tFragments N50:\t90298\n\tLargest frg:\t147965\n\tScaffolds:\t0\n\tMean coverage:\t16\n\n[2024-10-11 06:53:33] INFO: Final assembly: /galaxy/server/database/jobs_directory/000/120/working/out_dir/assembly.fasta\n",
    "job_messages": null,
    "dependencies": [],
    "job_metrics": []
}
