<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Results (powered by Planemo)"
           tests="45"
           errors="19"
           failures="5"
           skip="0">
    
    <testcase classname="bam_to_sam (Test #1)" name="0" time="34.451427936553955">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bam_to_sam (Test #2)" name="1" time="31.304544925689697">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bam_to_sam (Test #3)" name="2" time="9.740597486495972">
        
            <error type="error" message="Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: ."><![CDATA[
                { "execution_problem": "Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: .", "status": "error", "test_index": 2, "time_seconds": 9.740597486495972, "tool_id": "bam_to_sam", "tool_version": "2.0.4"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="bcftools_merge (Test #1)" name="0" time="35.28591060638428">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_merge (Test #2)" name="1" time="31.946682453155518">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_merge (Test #3)" name="2" time="26.33299708366394">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "input_files": [   {    "id": "bce5c4f2f95a1742",    "src": "hda"   },   {    "id": "d9096cbd6977fa25",    "src": "hda"   }  ],  "output_type": "v",  "sec_merge|force_samples": true,  "sec_merge|merge": "both" }, "job": {  "command_line": "export BCFTOOLS_PLUGINS=`which bcftools | sed \u0027s,bin/bcftools,libexec/bcftools,\u0027`;     bgzip -c \u0027/galaxy/server/database/objects/d/2/c/dataset_d2c09400-abdf-4719-8b4b-c625e18c0c35.dat\u0027 \u003e input0.vcf.gz \u0026\u0026 bcftools index input0.vcf.gz \u0026\u0026 echo \u0027input0.vcf.gz\u0027 \u003e\u003e vcfs_list \u0026\u0026  bgzip -c \u0027/galaxy/server/database/objects/9/b/e/dataset_9be0d511-0685-407d-8023-1b85e5555917.dat\u0027 \u003e input1.vcf.gz \u0026\u0026 bcftools index input1.vcf.gz \u0026\u0026 echo \u0027input1.vcf.gz\u0027 \u003e\u003e vcfs_list \u0026\u0026         bcftools merge    --force-samples   --merge \"both\"            --output-type \u0027v\u0027   --threads ${GALAXY_SLOTS:-4}    input0.vcf.gz input1.vcf.gz  \u003e \u0027/galaxy/server/database/objects/6/6/b/dataset_66b9790d-99f6-4f10-94d0-8faf9f65584e.dat\u0027",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2024-11-01T01:02:52.986052",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-gft4g",  "galaxy_version": "23.1",  "history_id": "f624892431083bb1",  "id": "3b1e76ad1d8c714d",  "inputs": {   "input_files": {    "id": "bce5c4f2f95a1742",    "src": "hda",    "uuid": "d2c09400-abdf-4719-8b4b-c625e18c0c35"   },   "input_files1": {    "id": "bce5c4f2f95a1742",    "src": "hda",    "uuid": "d2c09400-abdf-4719-8b4b-c625e18c0c35"   },   "input_files2": {    "id": "d9096cbd6977fa25",    "src": "hda",    "uuid": "9be0d511-0685-407d-8023-1b85e5555917"   }  },  "job_messages": null,  "job_metrics": [],  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "output_file": {    "id": "3b1e76ad1d8c714d",    "src": "hda",    "uuid": "66b9790d-99f6-4f10-94d0-8faf9f65584e"   }  },  "params": {   "__input_ext": "\"input\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "output_type": "\"v\"",   "sec_header": "{\"print_header\": false, \"use_header\": null}",   "sec_merge": "{\"force_samples\": true, \"info_rules\": null, \"merge\": \"both\", \"no_index\": false}",   "sec_restrict": "{\"apply_filters\": \"\", \"regions\": {\"__current_case__\": 0, \"regions_src\": \"__none__\"}, \"regions_overlap\": null}"  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/bcftools_merge/bcftools_merge/1.15.1+galaxy4",  "tool_stderr": "",  "tool_stdout": "",  "traceback": null,  "update_time": "2024-11-01T01:02:59.052443",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/bcftools_merge/bcftools_merge/1.15.1+galaxy4, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/bcftools_merge/bcftools_merge/1.15.1+galaxy4, exit_code: None, stderr: ." ], "status": "failure", "test_index": 2, "time_seconds": 26.33299708366394, "tool_id": "bcftools_merge", "tool_version": "1.15.1+galaxy4"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_merge (Test #4)" name="3" time="31.598908185958862">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_merge (Test #5)" name="4" time="31.62437677383423">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_merge (Test #6)" name="5" time="31.639204502105713">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [W::bcf_sr_add_reader] Using multiple unindexed files may produce errors, make sure chromosomes are in the same order!
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_merge (Test #7)" name="6" time="31.606333255767822">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="bcftools_plugin_missing2ref (Test #1)" name="0" time="39.24898338317871">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Filled 44 REF alleles
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="column_order_header_sort (Test #1)" name="0" time="0.140519380569458">
        
            <error type="error" message="Input staging problem: Test input file (in_1.tabular) cannot be found."><![CDATA[
                { "execution_problem": "Input staging problem: Test input file (in_1.tabular) cannot be found.", "status": "error", "test_index": 0, "time_seconds": 0.140519380569458, "tool_id": "column_order_header_sort", "tool_version": "0.0.1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="deeptools_plot_pca (Test #1)" name="0" time="47.574260234832764">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "advancedOpt|showAdvancedOpt": "yes",  "corData": {   "id": "3b309794db535ee6",   "src": "hda"  },  "outFileFormat": "png",  "plotTitle": "Test Plot" }, "job": {  "command_line": "plotPCA --corData \u0027/galaxy/server/database/objects/7/0/6/dataset_706d3086-dca7-4074-97f1-eb88e09f3ac0.dat\u0027 --plotTitle \u0027Test Plot\u0027 --plotFile \u0027/galaxy/server/database/objects/2/2/3/dataset_223aa8b9-ba68-4769-95bc-0fcb7de273c6.dat\u0027 --plotFileFormat \u0027png\u0027  --plotWidth \u002710.0\u0027 --plotHeight \u002710.0\u0027   --PCs 1 2 --ntop 1000",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2024-11-01T01:08:10.291656",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-g69f7",  "galaxy_version": "23.1",  "history_id": "f624892431083bb1",  "id": "e8334414c87f25d8",  "inputs": {   "corData": {    "id": "3b309794db535ee6",    "src": "hda",    "uuid": "706d3086-dca7-4074-97f1-eb88e09f3ac0"   }  },  "job_messages": null,  "job_metrics": [],  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "outFileName": {    "id": "e8334414c87f25d8",    "src": "hda",    "uuid": "223aa8b9-ba68-4769-95bc-0fcb7de273c6"   }  },  "params": {   "__input_ext": "\"input\"",   "advancedOpt": "{\"PCs\": \"1 2\", \"__current_case__\": 1, \"colors\": \"\", \"log2\": false, \"markers\": \"\", \"ntop\": \"1000\", \"plotHeight\": \"10.0\", \"plotWidth\": \"10.0\", \"rowCenter\": false, \"showAdvancedOpt\": \"yes\", \"transpose\": false}",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "outFileFormat": "\"png\"",   "outFileNameData": "false",   "plotTitle": "\"Test Plot\""  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_plot_pca/deeptools_plot_pca/3.5.4+galaxy0",  "tool_stderr": "",  "tool_stdout": "",  "traceback": null,  "update_time": "2024-11-01T01:08:39.485628",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_plot_pca/deeptools_plot_pca/3.5.4+galaxy0, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/bgruening/deeptools_plot_pca/deeptools_plot_pca/3.5.4+galaxy0, exit_code: None, stderr: ." ], "status": "failure", "test_index": 0, "time_seconds": 47.574260234832764, "tool_id": "deeptools_plot_pca", "tool_version": "3.5.4+galaxy0"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="deeptools_plot_pca (Test #2)" name="1" time="33.847532987594604">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="fastp (Test #1)" name="0" time="0.138962984085083">
        
            <error type="error" message="Input staging problem: Test input file (R1.fq) cannot be found."><![CDATA[
                { "execution_problem": "Input staging problem: Test input file (R1.fq) cannot be found.", "status": "error", "test_index": 0, "time_seconds": 0.138962984085083, "tool_id": "fastp", "tool_version": "0.23.4+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="fastp (Test #2)" name="1" time="0.07250452041625977">
        
            <error type="error" message="Input staging problem: Test input file (bwa-mem-fastq1.fq) cannot be found."><![CDATA[
                { "execution_problem": "Input staging problem: Test input file (bwa-mem-fastq1.fq) cannot be found.", "status": "error", "test_index": 1, "time_seconds": 0.07250452041625977, "tool_id": "fastp", "tool_version": "0.23.4+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="fastp (Test #11)" name="10" time="0.07469677925109863">
        
            <error type="error" message="Input staging problem: Test input file (R1.fq.gz) cannot be found."><![CDATA[
                { "execution_problem": "Input staging problem: Test input file (R1.fq.gz) cannot be found.", "status": "error", "test_index": 10, "time_seconds": 0.07469677925109863, "tool_id": "fastp", "tool_version": "0.23.4+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="fastp (Test #12)" name="11" time="0.07589244842529297">
        
            <error type="error" message="Input staging problem: Test input file (bwa-mem-fastq1.fq) cannot be found."><![CDATA[
                { "execution_problem": "Input staging problem: Test input file (bwa-mem-fastq1.fq) cannot be found.", "status": "error", "test_index": 11, "time_seconds": 0.07589244842529297, "tool_id": "fastp", "tool_version": "0.23.4+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="fastp (Test #3)" name="2" time="0.07415103912353516">
        
            <error type="error" message="Input staging problem: Test input file (R1.fq) cannot be found."><![CDATA[
                { "execution_problem": "Input staging problem: Test input file (R1.fq) cannot be found.", "status": "error", "test_index": 2, "time_seconds": 0.07415103912353516, "tool_id": "fastp", "tool_version": "0.23.4+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="fastp (Test #4)" name="3" time="0.07442069053649902">
        
            <error type="error" message="Input staging problem: Test input file (R1.fq) cannot be found."><![CDATA[
                { "execution_problem": "Input staging problem: Test input file (R1.fq) cannot be found.", "status": "error", "test_index": 3, "time_seconds": 0.07442069053649902, "tool_id": "fastp", "tool_version": "0.23.4+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="fastp (Test #5)" name="4" time="0.07431745529174805">
        
            <error type="error" message="Input staging problem: Test input file (R1.fq) cannot be found."><![CDATA[
                { "execution_problem": "Input staging problem: Test input file (R1.fq) cannot be found.", "status": "error", "test_index": 4, "time_seconds": 0.07431745529174805, "tool_id": "fastp", "tool_version": "0.23.4+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="fastp (Test #6)" name="5" time="0.0730733871459961">
        
            <error type="error" message="Input staging problem: Test input file (bwa-mem-fastq1.fq) cannot be found."><![CDATA[
                { "execution_problem": "Input staging problem: Test input file (bwa-mem-fastq1.fq) cannot be found.", "status": "error", "test_index": 5, "time_seconds": 0.0730733871459961, "tool_id": "fastp", "tool_version": "0.23.4+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="fastp (Test #7)" name="6" time="0.0733945369720459">
        
            <error type="error" message="Input staging problem: Test input file (bwa-mem-fastq1.fq) cannot be found."><![CDATA[
                { "execution_problem": "Input staging problem: Test input file (bwa-mem-fastq1.fq) cannot be found.", "status": "error", "test_index": 6, "time_seconds": 0.0733945369720459, "tool_id": "fastp", "tool_version": "0.23.4+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="fastp (Test #8)" name="7" time="0.07454061508178711">
        
            <error type="error" message="Input staging problem: Test input file (bwa-mem-fastq1.fq) cannot be found."><![CDATA[
                { "execution_problem": "Input staging problem: Test input file (bwa-mem-fastq1.fq) cannot be found.", "status": "error", "test_index": 7, "time_seconds": 0.07454061508178711, "tool_id": "fastp", "tool_version": "0.23.4+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="fastp (Test #9)" name="8" time="0.07280755043029785">
        
            <error type="error" message="Input staging problem: Test input file (R1.fq) cannot be found."><![CDATA[
                { "execution_problem": "Input staging problem: Test input file (R1.fq) cannot be found.", "status": "error", "test_index": 8, "time_seconds": 0.07280755043029785, "tool_id": "fastp", "tool_version": "0.23.4+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="fastp (Test #10)" name="9" time="0.08000755310058594">
        
            <error type="error" message="Input staging problem: Test input file (R1.fq.gz) cannot be found."><![CDATA[
                { "execution_problem": "Input staging problem: Test input file (R1.fq.gz) cannot be found.", "status": "error", "test_index": 9, "time_seconds": 0.08000755310058594, "tool_id": "fastp", "tool_version": "0.23.4+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="ivar_variants (Test #1)" name="0" time="12.48291015625">
        
            <error type="error" message="Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: ."><![CDATA[
                { "execution_problem": "Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: .", "status": "error", "test_index": 0, "time_seconds": 12.48291015625, "tool_id": "ivar_variants", "tool_version": "1.4.3+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="ivar_variants (Test #2)" name="1" time="40.72453284263611">
        
            
            <system-out><![CDATA[
            A GFF file containing the open reading frames (ORFs) has not been provided. Amino acid translation will not be done.A reference sequence has not been supplied. Amino acid translation will not be done.sampleDELINSSNPvariants0115
            ]]></system-out>
            <system-err><![CDATA[
            [mpileup] 1 samples in 1 input files[mpileup] Max depth set to maximum value (2147483647)
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="ivar_variants (Test #3)" name="2" time="34.857027769088745">
        
            
            <system-out><![CDATA[
            A GFF file containing the open reading frames (ORFs) has not been provided. Amino acid translation will not be done.A reference sequence has not been supplied. Amino acid translation will not be done.sampleDELINSSNPvariants0010
            ]]></system-out>
            <system-err><![CDATA[
            [mpileup] 1 samples in 1 input files[mpileup] Max depth set to maximum value (2147483647)
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="ivar_variants (Test #4)" name="3" time="17.994330883026123">
        
            <error type="error" message="Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: ."><![CDATA[
                { "execution_problem": "Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: .", "status": "error", "test_index": 3, "time_seconds": 17.994330883026123, "tool_id": "ivar_variants", "tool_version": "1.4.3+galaxy1"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="ivar_variants (Test #5)" name="4" time="32.00865626335144">
        
            
                <error type="error" message="Tool exit code: None"><![CDATA[
                    { "inputs": {  "input_bam": {   "id": "f2f94c2bf80fd57b",   "src": "hda"  },  "output_format|choice": "tabular_and_vcf",  "output_format|gtf": {   "id": "4dbca14d22beddfd",   "src": "hda"  },  "output_format|pass_only": true,  "ref": {   "id": "5551b9ee2ba71bcc",   "src": "hda"  } }, "job": {  "command_line": "ln -s \u0027/galaxy/server/database/objects/0/d/f/dataset_0df3e2e4-01d6-4720-824c-aec141922021.dat\u0027 ref.fa \u0026\u0026 ln -s \u0027/galaxy/server/database/objects/a/7/6/dataset_a767f5de-b0e5-4fb6-a442-4d008811d956.dat\u0027 sorted.bam \u0026\u0026 samtools mpileup -A -d 0 --reference ref.fa -B -Q 0 sorted.bam | ivar variants -p variants -q 20 -t 0.03 -r ref.fa -g \u0027/galaxy/server/database/objects/a/5/d/dataset_a5d56749-84a5-4bb4-a4ce-647b819a1f4a.dat\u0027 \u0026\u0026 python \u0027/cvmfs/cloud.galaxyproject.org/tools/toolshed.g2.bx.psu.edu/repos/iuc/ivar_variants/abbc8041e8ec/ivar_variants/ivar_variants_to_vcf.py\u0027 --pass_only variants.tsv variants.vcf",  "command_version": null,  "copied_from_job_id": null,  "create_time": "2024-11-01T01:12:29.671070",  "dependencies": [],  "exit_code": null,  "external_id": "gxy-pfkk5",  "galaxy_version": "23.1",  "history_id": "f624892431083bb1",  "id": "5551b9ee2ba71bcc",  "inputs": {   "input_bam": {    "id": "f2f94c2bf80fd57b",    "src": "hda",    "uuid": "a767f5de-b0e5-4fb6-a442-4d008811d956"   },   "output_format|gtf": {    "id": "4dbca14d22beddfd",    "src": "hda",    "uuid": "a5d56749-84a5-4bb4-a4ce-647b819a1f4a"   },   "ref": {    "id": "5551b9ee2ba71bcc",    "src": "hda",    "uuid": "0df3e2e4-01d6-4720-824c-aec141922021"   }  },  "job_messages": null,  "job_metrics": [],  "job_stderr": null,  "job_stdout": null,  "model_class": "Job",  "output_collections": {},  "outputs": {   "output_variants_tabular": {    "id": "a6bcc30d4b1494f6",    "src": "hda",    "uuid": "1792e2a7-58b7-490a-892f-38785c5e6e46"   },   "output_variants_vcf": {    "id": "f49e3da29de5bb46",    "src": "hda",    "uuid": "766f02ba-7726-49bf-80d0-2a24c13c8853"   }  },  "params": {   "__input_ext": "\"input\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "min_freq": "\"0.03\"",   "min_qual": "\"20\"",   "output_format": "{\"__current_case__\": 1, \"choice\": \"tabular_and_vcf\", \"gtf\": {\"values\": [{\"id\": 78, \"src\": \"hda\"}]}, \"pass_only\": true}"  },  "state": "error",  "stderr": "",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/ivar_variants/ivar_variants/1.4.3+galaxy1",  "tool_stderr": "",  "tool_stdout": "",  "traceback": null,  "update_time": "2024-11-01T01:12:37.252092",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/ivar_variants/ivar_variants/1.4.3+galaxy1, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/ivar_variants/ivar_variants/1.4.3+galaxy1, exit_code: None, stderr: .",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/ivar_variants/ivar_variants/1.4.3+galaxy1, exit_code: None, stderr: ." ], "status": "failure", "test_index": 4, "time_seconds": 32.00865626335144, "tool_id": "ivar_variants", "tool_version": "1.4.3+galaxy1"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="lofreq_viterbi (Test #1)" name="0" time="19.481343030929565">
        
            <error type="error" message="Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: ."><![CDATA[
                { "execution_problem": "Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: .", "status": "error", "test_index": 0, "time_seconds": 19.481343030929565, "tool_id": "lofreq_viterbi", "tool_version": "2.1.5+galaxy0"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="lofreq_viterbi (Test #2)" name="1" time="44.19186615943909">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [bam_sort_core] merging from 0 files and 4 in-memory blocks...
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="poretools_events (Test #1)" name="0" time="56.63960075378418">
        
            
                <error type="error" message="Tool exit code: 1"><![CDATA[
                    { "inputs": {  "input": {   "id": "9822c726418aeb2d",   "src": "hda"  },  "precalled": false }, "job": {  "command_line": "poretools events  \u0027/galaxy/server/database/objects/9/6/e/dataset_96e9a25f-4fff-4338-8120-69f6e6eb59b2.dat\u0027 \u003e \u0027/galaxy/server/database/objects/2/0/1/dataset_201f39d1-1c4f-4050-b351-063958c9a775.dat\u0027",  "command_version": "",  "copied_from_job_id": null,  "create_time": "2024-11-01T01:06:38.882336",  "dependencies": [],  "exit_code": 1,  "external_id": "gxy-kpwxg",  "galaxy_version": "23.1",  "history_id": "f624892431083bb1",  "id": "c08d80845bf3f1bd",  "inputs": {   "input": {    "id": "9822c726418aeb2d",    "src": "hda",    "uuid": "96e9a25f-4fff-4338-8120-69f6e6eb59b2"   }  },  "job_messages": [   {    "code_desc": "",    "desc": "Fatal error: Exit code 1 ()",    "error_level": 3,    "exit_code": 1,    "type": "exit_code"   },   {    "code_desc": "",    "desc": "Fatal error: ",    "error_level": 3,    "match": "Error:",    "stream": "stderr",    "type": "regex"   }  ],  "job_metrics": [   {    "name": "runtime_seconds",    "plugin": "core",    "raw_value": "1.0000000",    "title": "Job Runtime (Wall Clock)",    "value": "1 second"   },   {    "name": "end_epoch",    "plugin": "core",    "raw_value": "1730423220.0000000",    "title": "Job End Time",    "value": "2024-11-01 01:07:00"   },   {    "name": "start_epoch",    "plugin": "core",    "raw_value": "1730423219.0000000",    "title": "Job Start Time",    "value": "2024-11-01 01:06:59"   },   {    "name": "galaxy_memory_mb",    "plugin": "core",    "raw_value": "12240.0000000",    "title": "Memory Allocated (MB)",    "value": "12240"   },   {    "name": "galaxy_slots",    "plugin": "core",    "raw_value": "1.0000000",    "title": "Cores Allocated",    "value": "1"   }  ],  "job_stderr": "",  "job_stdout": "",  "model_class": "Job",  "output_collections": {},  "outputs": {   "output": {    "id": "c08d80845bf3f1bd",    "src": "hda",    "uuid": "201f39d1-1c4f-4050-b351-063958c9a775"   }  },  "params": {   "__input_ext": "\"fast5.tar\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "precalled": "false"  },  "state": "error",  "stderr": "Traceback (most recent call last):\n  File \"/usr/local/bin/poretools\", line 11, in \u003cmodule\u003e\n    load_entry_point(\u0027poretools==0.6.0\u0027, \u0027console_scripts\u0027, \u0027poretools\u0027)()\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 543, in main\n    args.func(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 55, in run_subtool\n    submodule.run(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/events.py\", line 17, in run\n    for fast5 in Fast5File.Fast5FileSet(args.files):\n  File \"/usr/local/lib/python2.7/site-packages/poretools/Fast5File.py\", line 110, in next\n    shutil.rmtree(PORETOOLS_TMPDIR)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 261, in rmtree\n    rmtree(fullname, ignore_errors, onerror)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 270, in rmtree\n    onerror(os.rmdir, path, sys.exc_info())\n  File \"/usr/local/lib/python2.7/shutil.py\", line 268, in rmtree\n    os.rmdir(path)\nOSError: [Errno 39] Directory not empty: \u0027.poretools_tmp/test-data\u0027\n",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/poretools_events/poretools_events/0.6.1a1.1",  "tool_stderr": "Traceback (most recent call last):\n  File \"/usr/local/bin/poretools\", line 11, in \u003cmodule\u003e\n    load_entry_point(\u0027poretools==0.6.0\u0027, \u0027console_scripts\u0027, \u0027poretools\u0027)()\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 543, in main\n    args.func(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 55, in run_subtool\n    submodule.run(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/events.py\", line 17, in run\n    for fast5 in Fast5File.Fast5FileSet(args.files):\n  File \"/usr/local/lib/python2.7/site-packages/poretools/Fast5File.py\", line 110, in next\n    shutil.rmtree(PORETOOLS_TMPDIR)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 261, in rmtree\n    rmtree(fullname, ignore_errors, onerror)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 270, in rmtree\n    onerror(os.rmdir, path, sys.exc_info())\n  File \"/usr/local/lib/python2.7/shutil.py\", line 268, in rmtree\n    os.rmdir(path)\nOSError: [Errno 39] Directory not empty: \u0027.poretools_tmp/test-data\u0027\n",  "tool_stdout": "",  "traceback": null,  "update_time": "2024-11-01T01:07:17.131502",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/poretools_events/poretools_events/0.6.1a1.1, exit_code: 1, stderr: Traceback (most recent call last):\n  File \"/usr/local/bin/poretools\", line 11, in \u003cmodule\u003e\n    load_entry_point(\u0027poretools==0.6.0\u0027, \u0027console_scripts\u0027, \u0027poretools\u0027)()\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 543, in main\n    args.func(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 55, in run_subtool\n    submodule.run(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/events.py\", line 17, in run\n    for fast5 in Fast5File.Fast5FileSet(args.files):\n  File \"/usr/local/lib/python2.7/site-packages/poretools/Fast5File.py\", line 110, in next\n    shutil.rmtree(PORETOOLS_TMPDIR)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 261, in rmtree\n    rmtree(fullname, ignore_errors, onerror)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 270, in rmtree\n    onerror(os.rmdir, path, sys.exc_info())\n  File \"/usr/local/lib/python2.7/shutil.py\", line 268, in rmtree\n    os.rmdir(path)\nOSError: [Errno 39] Directory not empty: \u0027.poretools_tmp/test-data\u0027\n.",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/poretools_events/poretools_events/0.6.1a1.1, exit_code: 1, stderr: Traceback (most recent call last):\n  File \"/usr/local/bin/poretools\", line 11, in \u003cmodule\u003e\n    load_entry_point(\u0027poretools==0.6.0\u0027, \u0027console_scripts\u0027, \u0027poretools\u0027)()\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 543, in main\n    args.func(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 55, in run_subtool\n    submodule.run(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/events.py\", line 17, in run\n    for fast5 in Fast5File.Fast5FileSet(args.files):\n  File \"/usr/local/lib/python2.7/site-packages/poretools/Fast5File.py\", line 110, in next\n    shutil.rmtree(PORETOOLS_TMPDIR)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 261, in rmtree\n    rmtree(fullname, ignore_errors, onerror)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 270, in rmtree\n    onerror(os.rmdir, path, sys.exc_info())\n  File \"/usr/local/lib/python2.7/shutil.py\", line 268, in rmtree\n    os.rmdir(path)\nOSError: [Errno 39] Directory not empty: \u0027.poretools_tmp/test-data\u0027\n." ], "status": "failure", "test_index": 0, "time_seconds": 56.63960075378418, "tool_id": "poretools_events", "tool_version": "0.6.1a1.1"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Traceback (most recent call last):  File "/usr/local/bin/poretools", line 11, in <module>    load_entry_point('poretools==0.6.0', 'console_scripts', 'poretools')()  File "/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py", line 543, in main    args.func(parser, args)  File "/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py", line 55, in run_subtool    submodule.run(parser, args)  File "/usr/local/lib/python2.7/site-packages/poretools/events.py", line 17, in run    for fast5 in Fast5File.Fast5FileSet(args.files):  File "/usr/local/lib/python2.7/site-packages/poretools/Fast5File.py", line 110, in next    shutil.rmtree(PORETOOLS_TMPDIR)  File "/usr/local/lib/python2.7/shutil.py", line 261, in rmtree    rmtree(fullname, ignore_errors, onerror)  File "/usr/local/lib/python2.7/shutil.py", line 270, in rmtree    onerror(os.rmdir, path, sys.exc_info())  File "/usr/local/lib/python2.7/shutil.py", line 268, in rmtree    os.rmdir(path)OSError: [Errno 39] Directory not empty: '.poretools_tmp/test-data'
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="poretools_events (Test #2)" name="1" time="32.944586515426636">
        
            
                <error type="error" message="Tool exit code: 1"><![CDATA[
                    { "inputs": {  "input": {   "id": "24e7b7275b19c74c",   "src": "hda"  },  "precalled": true }, "job": {  "command_line": "poretools events --pre-basecalled \u0027/galaxy/server/database/objects/d/3/8/dataset_d38e5338-0c21-4737-a636-b09923b971f6.dat\u0027 \u003e \u0027/galaxy/server/database/objects/5/1/6/dataset_516050cf-44fa-43f8-b2e6-e746cc640e96.dat\u0027",  "command_version": "",  "copied_from_job_id": null,  "create_time": "2024-11-01T01:07:35.181654",  "dependencies": [],  "exit_code": 1,  "external_id": "gxy-sd9jc",  "galaxy_version": "23.1",  "history_id": "f624892431083bb1",  "id": "aee1c96f63ccd38f",  "inputs": {   "input": {    "id": "24e7b7275b19c74c",    "src": "hda",    "uuid": "d38e5338-0c21-4737-a636-b09923b971f6"   }  },  "job_messages": [   {    "code_desc": "",    "desc": "Fatal error: Exit code 1 ()",    "error_level": 3,    "exit_code": 1,    "type": "exit_code"   },   {    "code_desc": "",    "desc": "Fatal error: ",    "error_level": 3,    "match": "Error:",    "stream": "stderr",    "type": "regex"   }  ],  "job_metrics": [   {    "name": "runtime_seconds",    "plugin": "core",    "raw_value": "1.0000000",    "title": "Job Runtime (Wall Clock)",    "value": "1 second"   },   {    "name": "end_epoch",    "plugin": "core",    "raw_value": "1730423258.0000000",    "title": "Job End Time",    "value": "2024-11-01 01:07:38"   },   {    "name": "start_epoch",    "plugin": "core",    "raw_value": "1730423257.0000000",    "title": "Job Start Time",    "value": "2024-11-01 01:07:37"   },   {    "name": "galaxy_memory_mb",    "plugin": "core",    "raw_value": "12240.0000000",    "title": "Memory Allocated (MB)",    "value": "12240"   },   {    "name": "galaxy_slots",    "plugin": "core",    "raw_value": "1.0000000",    "title": "Cores Allocated",    "value": "1"   }  ],  "job_stderr": "",  "job_stdout": "",  "model_class": "Job",  "output_collections": {},  "outputs": {   "output": {    "id": "aee1c96f63ccd38f",    "src": "hda",    "uuid": "516050cf-44fa-43f8-b2e6-e746cc640e96"   }  },  "params": {   "__input_ext": "\"fast5.tar\"",   "chromInfo": "\"/cvmfs/data.galaxyproject.org/managed/len/ucsc/?.len\"",   "dbkey": "\"?\"",   "precalled": "true"  },  "state": "error",  "stderr": "Traceback (most recent call last):\n  File \"/usr/local/bin/poretools\", line 11, in \u003cmodule\u003e\n    load_entry_point(\u0027poretools==0.6.0\u0027, \u0027console_scripts\u0027, \u0027poretools\u0027)()\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 543, in main\n    args.func(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 55, in run_subtool\n    submodule.run(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/events.py\", line 13, in run\n    for fast5 in Fast5File.Fast5FileSet(args.files):\n  File \"/usr/local/lib/python2.7/site-packages/poretools/Fast5File.py\", line 110, in next\n    shutil.rmtree(PORETOOLS_TMPDIR)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 261, in rmtree\n    rmtree(fullname, ignore_errors, onerror)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 270, in rmtree\n    onerror(os.rmdir, path, sys.exc_info())\n  File \"/usr/local/lib/python2.7/shutil.py\", line 268, in rmtree\n    os.rmdir(path)\nOSError: [Errno 39] Directory not empty: \u0027.poretools_tmp/test-data\u0027\n",  "stdout": "",  "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/poretools_events/poretools_events/0.6.1a1.1",  "tool_stderr": "Traceback (most recent call last):\n  File \"/usr/local/bin/poretools\", line 11, in \u003cmodule\u003e\n    load_entry_point(\u0027poretools==0.6.0\u0027, \u0027console_scripts\u0027, \u0027poretools\u0027)()\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 543, in main\n    args.func(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 55, in run_subtool\n    submodule.run(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/events.py\", line 13, in run\n    for fast5 in Fast5File.Fast5FileSet(args.files):\n  File \"/usr/local/lib/python2.7/site-packages/poretools/Fast5File.py\", line 110, in next\n    shutil.rmtree(PORETOOLS_TMPDIR)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 261, in rmtree\n    rmtree(fullname, ignore_errors, onerror)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 270, in rmtree\n    onerror(os.rmdir, path, sys.exc_info())\n  File \"/usr/local/lib/python2.7/shutil.py\", line 268, in rmtree\n    os.rmdir(path)\nOSError: [Errno 39] Directory not empty: \u0027.poretools_tmp/test-data\u0027\n",  "tool_stdout": "",  "traceback": null,  "update_time": "2024-11-01T01:07:49.919072",  "user_email": "tests@fake.org" }, "output_problems": [  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/poretools_events/poretools_events/0.6.1a1.1, exit_code: 1, stderr: Traceback (most recent call last):\n  File \"/usr/local/bin/poretools\", line 11, in \u003cmodule\u003e\n    load_entry_point(\u0027poretools==0.6.0\u0027, \u0027console_scripts\u0027, \u0027poretools\u0027)()\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 543, in main\n    args.func(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 55, in run_subtool\n    submodule.run(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/events.py\", line 13, in run\n    for fast5 in Fast5File.Fast5FileSet(args.files):\n  File \"/usr/local/lib/python2.7/site-packages/poretools/Fast5File.py\", line 110, in next\n    shutil.rmtree(PORETOOLS_TMPDIR)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 261, in rmtree\n    rmtree(fullname, ignore_errors, onerror)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 270, in rmtree\n    onerror(os.rmdir, path, sys.exc_info())\n  File \"/usr/local/lib/python2.7/shutil.py\", line 268, in rmtree\n    os.rmdir(path)\nOSError: [Errno 39] Directory not empty: \u0027.poretools_tmp/test-data\u0027\n.",  "Job in error state.. tool_id: toolshed.g2.bx.psu.edu/repos/iuc/poretools_events/poretools_events/0.6.1a1.1, exit_code: 1, stderr: Traceback (most recent call last):\n  File \"/usr/local/bin/poretools\", line 11, in \u003cmodule\u003e\n    load_entry_point(\u0027poretools==0.6.0\u0027, \u0027console_scripts\u0027, \u0027poretools\u0027)()\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 543, in main\n    args.func(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py\", line 55, in run_subtool\n    submodule.run(parser, args)\n  File \"/usr/local/lib/python2.7/site-packages/poretools/events.py\", line 13, in run\n    for fast5 in Fast5File.Fast5FileSet(args.files):\n  File \"/usr/local/lib/python2.7/site-packages/poretools/Fast5File.py\", line 110, in next\n    shutil.rmtree(PORETOOLS_TMPDIR)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 261, in rmtree\n    rmtree(fullname, ignore_errors, onerror)\n  File \"/usr/local/lib/python2.7/shutil.py\", line 270, in rmtree\n    onerror(os.rmdir, path, sys.exc_info())\n  File \"/usr/local/lib/python2.7/shutil.py\", line 268, in rmtree\n    os.rmdir(path)\nOSError: [Errno 39] Directory not empty: \u0027.poretools_tmp/test-data\u0027\n." ], "status": "failure", "test_index": 1, "time_seconds": 32.944586515426636, "tool_id": "poretools_events", "tool_version": "0.6.1a1.1"}
                ]]></error>
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            Traceback (most recent call last):  File "/usr/local/bin/poretools", line 11, in <module>    load_entry_point('poretools==0.6.0', 'console_scripts', 'poretools')()  File "/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py", line 543, in main    args.func(parser, args)  File "/usr/local/lib/python2.7/site-packages/poretools/poretools_main.py", line 55, in run_subtool    submodule.run(parser, args)  File "/usr/local/lib/python2.7/site-packages/poretools/events.py", line 13, in run    for fast5 in Fast5File.Fast5FileSet(args.files):  File "/usr/local/lib/python2.7/site-packages/poretools/Fast5File.py", line 110, in next    shutil.rmtree(PORETOOLS_TMPDIR)  File "/usr/local/lib/python2.7/shutil.py", line 261, in rmtree    rmtree(fullname, ignore_errors, onerror)  File "/usr/local/lib/python2.7/shutil.py", line 270, in rmtree    onerror(os.rmdir, path, sys.exc_info())  File "/usr/local/lib/python2.7/shutil.py", line 268, in rmtree    os.rmdir(path)OSError: [Errno 39] Directory not empty: '.poretools_tmp/test-data'
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_merge (Test #1)" name="0" time="104.99652409553528">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_merge (Test #2)" name="1" time="35.862608671188354">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [bam_translate] PG tag "colt" on read "r001" encountered with no corresponding entry in header, tag lost. Unknown tags are only reported once per input file for each tag ID.
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_merge (Test #3)" name="2" time="31.578115701675415">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="samtools_merge (Test #4)" name="3" time="13.206526517868042">
        
            <error type="error" message="Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: ."><![CDATA[
                { "execution_problem": "Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: .", "status": "error", "test_index": 3, "time_seconds": 13.206526517868042, "tool_id": "samtools_merge", "tool_version": "1.9"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="samtools_merge (Test #5)" name="4" time="32.98934292793274">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            [bam_translate] PG tag "colt" on read "r001" encountered with no corresponding entry in header, tag lost. Unknown tags are only reported once per input file for each tag ID.
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="vcfannotategenotypes (Test #1)" name="0" time="38.08243799209595">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="vcfsort (Test #1)" name="0" time="33.411221504211426">
        
            
            <system-out><![CDATA[
            
            ]]></system-out>
            <system-err><![CDATA[
            
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="volcanoplot (Test #1)" name="0" time="54.0731565952301">
        
            
            <system-out><![CDATA[
            [1] "Header row detected"null device           1 R version 4.0.5 (2021-03-31)Platform: x86_64-conda-linux-gnu (64-bit)Running under: Debian GNU/Linux 10 (buster)Matrix products: defaultBLAS/LAPACK: /usr/local/lib/libopenblasp-r0.3.15.solocale: [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          [10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   attached base packages:[1] stats     graphics  grDevices utils     datasets  methods   base     other attached packages:[1] ggrepel_0.9.1 ggplot2_3.3.3 dplyr_1.0.6  loaded via a namespace (and not attached): [1] Rcpp_1.0.6       magrittr_2.0.1   tidyselect_1.1.1 munsell_0.5.0    [5] colorspace_2.0-1 R6_2.5.0         rlang_0.4.11     fansi_0.5.0      [9] grid_4.0.5       gtable_0.3.0     utf8_1.2.1       withr_2.4.2     [13] ellipsis_0.3.2   digest_0.6.27    tibble_3.1.2     lifecycle_1.0.0 [17] crayon_1.4.1     purrr_0.3.4      farver_2.1.0     vctrs_0.3.8     [21] glue_1.4.2       labeling_0.4.2   compiler_4.0.5   pillar_1.6.1    [25] generics_0.1.0   scales_1.1.1     pkgconfig_2.0.3 
            ]]></system-out>
            <system-err><![CDATA[
            Warning message:In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :  OS reports request to set locale to "en_US.UTF-8" cannot be honored
            ]]></system-err>
        
    </testcase>
    
    <testcase classname="volcanoplot (Test #2)" name="1" time="11.153218030929565">
        
            <error type="error" message="Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: ."><![CDATA[
                { "execution_problem": "Input staging problem: Job in error state.. tool_id: upload1, exit_code: None, stderr: .", "status": "error", "test_index": 1, "time_seconds": 11.153218030929565, "tool_id": "volcanoplot", "tool_version": "0.0.6"}
            ]]></error>
        
    </testcase>
    
    <testcase classname="volcanoplot (Test #3)" name="2" time="37.909223556518555">
        
            
            <system-out><![CDATA[
            null device           1 R version 4.0.5 (2021-03-31)Platform: x86_64-conda-linux-gnu (64-bit)Running under: Debian GNU/Linux 10 (buster)Matrix products: defaultBLAS/LAPACK: /usr/local/lib/libopenblasp-r0.3.15.solocale: [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          [10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   attached base packages:[1] stats     graphics  grDevices utils     datasets  methods   base     other attached packages:[1] ggrepel_0.9.1 ggplot2_3.3.3 dplyr_1.0.6  loaded via a namespace (and not attached): [1] Rcpp_1.0.6       magrittr_2.0.1   tidyselect_1.1.1 munsell_0.5.0    [5] colorspace_2.0-1 R6_2.5.0         rlang_0.4.11     fansi_0.5.0      [9] grid_4.0.5       gtable_0.3.0     utf8_1.2.1       withr_2.4.2     [13] ellipsis_0.3.2   digest_0.6.27    tibble_3.1.2     lifecycle_1.0.0 [17] crayon_1.4.1     purrr_0.3.4      farver_2.1.0     vctrs_0.3.8     [21] glue_1.4.2       labeling_0.4.2   compiler_4.0.5   pillar_1.6.1    [25] generics_0.1.0   scales_1.1.1     pkgconfig_2.0.3 
            ]]></system-out>
            <system-err><![CDATA[
            Warning message:In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :  OS reports request to set locale to "en_US.UTF-8" cannot be honored
            ]]></system-err>
        
    </testcase>
    
</testsuite>